// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Neon 需要直连用于 prisma db push / migrate
    ...(process.env["DIRECT_DATABASE_URL"] && {
      directUrl: process.env["DIRECT_DATABASE_URL"],
    }),
  },
});
